/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.pa.unicam.stronatisamuele115894;

import it.pa.unicam.stronatisamuele115894.controller.MapBasedSession;
import it.pa.unicam.stronatisamuele115894.controller.SessionController;
import it.pa.unicam.stronatisamuele115894.controller.SessionInjector;
import it.pa.unicam.stronatisamuele115894.controller.StreamBasedSessionController;
import it.pa.unicam.stronatisamuele115894.view.ConsoleView;
import it.pa.unicam.stronatisamuele115894.view.View;
import javafx.application.Application;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Objects;

public class App {

    private final View view;

    public enum SESSION_TYPE {
        CONSOLE,
    }

    public App(View view) throws IOException{
        this.view = view;
        start();
    }

    public void start() throws IOException {
        view.open();
    }


    public static void main(String[] args) throws IOException{
        if (args.length == 0)
            launchGui();
        else {
            try {
                Objects.requireNonNull(createSessionInterface(args[0]));
            } catch (IllegalArgumentException e) {
                System.err.println("Cannot create this kind of session!");
            }
        }
    }

    private static App createSessionInterface(String code) throws IOException{
        switch (SESSION_TYPE.valueOf(code.toUpperCase())) {
            case CONSOLE:
                return createDefaultConsoleSession();
        }
        return null;
    }

    private static App createDefaultConsoleSession() throws IOException {
        SessionController controller = new StreamBasedSessionController(
                new MapBasedSession(SessionInjector.provideTurtle(),SessionInjector.provideCommands()));
        return new App(new ConsoleView(controller));
    }

    private static void launchGui() {
        Application.launch(JavaFXLogo.class);
    }
}
